# Generated by Django 5.2.4 on 2025-07-03 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_number", models.IntegerField()),
                ("patient_name", models.CharField(max_length=255)),
                (
                    "patient_gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("visit_date", models.DateField(default=datetime.date.today)),
                (
                    "status",
                    models.CharField(
                        choices=[("WAITING", "Waiting"), ("DONE", "Done")],
                        default="WAITING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["visit_date", "token_number"],
                "unique_together": {("token_number", "visit_date")},
            },
        ),
    ]
