# Generated by Django 5.2.4 on 2025-07-05 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Queue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="visit",
            options={"ordering": ["visit_date", "queue", "token_number"]},
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "registration_number",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, null=True)
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["phone"], name="api_patient_phone_9d1c6b_idx"
                    ),
                    models.Index(
                        fields=["name"], name="api_patient_name_8aa05a_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="visit",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to="api.patient",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visit",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="visit",
            name="queue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to="api.queue",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visit",
            unique_together={("token_number", "visit_date", "queue")},
        ),
    ]
