# Generated by Django 5.2.4 on 2025-08-18 21:27

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_QUEUE_NAME = "General"


def ensure_patient_queue(apps, schema_editor):
    Visit = apps.get_model("api", "Visit")
    Patient = apps.get_model("api", "Patient")
    Queue = apps.get_model("api", "Queue")
    db_alias = schema_editor.connection.alias

    general_queue, _ = Queue.objects.using(db_alias).get_or_create(
        name=DEFAULT_QUEUE_NAME
    )

    visits = Visit.objects.using(db_alias).filter(
        models.Q(patient__isnull=True) | models.Q(queue__isnull=True)
    )
    for visit in visits:
        if visit.patient_id is None:
            name = getattr(visit, "patient_name", None) or "Unknown"
            gender = getattr(visit, "patient_gender", None) or "OTHER"
            anon_patient, _ = Patient.objects.using(db_alias).get_or_create(
                name=name,
                gender=gender,
                defaults={"phone": None},
            )
            visit.patient = anon_patient
        if visit.queue_id is None:
            visit.queue = general_queue
        visit.save(using=db_alias)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_backfill_visits_to_patients_queues"),
    ]

    operations = [
        migrations.RunPython(ensure_patient_queue, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="visit",
            name="patient_gender",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="patient_name",
        ),
        migrations.AlterField(
            model_name="visit",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to="api.patient",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to="api.queue",
            ),
        ),
    ]
