# Generated by Django 5.2.4 on 2025-09-12 11:17

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.bulk_create(
        [
            Group(name="Admin"),
            Group(name="Doctor"),
            Group(name="Assistant"),
            Group(name="Display"),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_visit_status"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
