# Generated by Django 5.2.4 on 2025-09-12 11:17

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    canonical_groups = ["admin", "doctor", "assistant", "display"]

    for group_name in canonical_groups:
        existing_group = Group.objects.filter(name__iexact=group_name).order_by("id").first()
        if existing_group:
            if existing_group.name != group_name:
                existing_group.name = group_name
                existing_group.save(update_fields=["name"])
        else:
            Group.objects.create(name=group_name)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_visit_status"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
