# Generated by Django 5.2.4 on 2025-09-25 17:23

import api.models
from django.db import migrations, models


def convert_registration_numbers_to_formatted(apps, schema_editor):
    """Convert existing integer registration numbers to xx-xx-xxx format"""


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20250912_1117"),
    ]

    operations = [
        # Step 1: Change field to CharField but without validators first
        migrations.AlterField(
            model_name="patient",
            name="registration_number",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, unique=True
            ),
        ),
        # Step 2: Convert existing data
        migrations.RunPython(
            convert_registration_numbers_to_formatted,
            reverse_conversion,
        ),
        # Step 3: Add the validators
        migrations.AlterField(
            model_name="patient",
            name="registration_number",
            field=models.CharField(
                max_length=8,
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[api.models.validate_registration_number_format],
            ),
        ),
    ]
