# Generated by Django 5.2.4 on 2025-08-18 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_visit_patient_gender_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drive_file_id", models.CharField(blank=True, max_length=255)),
                ("image_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_images",
                        to="api.visit",
                    ),
                ),
            ],
        ),
    ]
