# Generated by Django 5.2.4 on 2025-09-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_prescriptionimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING", "Waiting"),
                    ("START", "Start"),
                    ("IN_ROOM", "In Room"),
                    ("DONE", "Done"),
                ],
                default="WAITING",
                max_length=10,
            ),
        ),
    ]
