# Generated by Django 5.2.4 on 2025-10-04 23:20

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_bootstrap_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="registration_number",
            field=models.CharField(
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[api.models.validate_registration_number_format],
            ),
        ),
    ]
