name: Backend CI

on:
  push:
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend-ci.yml'
      - 'tooling/linting/**'
  pull_request:
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend-ci.yml'
      - 'tooling/linting/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        working-directory: apps/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run backend lint
        working-directory: apps/backend
        run: flake8 .

      - name: Run backend tests
        working-directory: apps/backend
        run: pytest
