name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r clinicq_backend/requirements.txt
          pip install -r clinicq_backend/requirements-dev.txt

      - name: Lint backend with flake8
        run: flake8 .
        working-directory: clinicq_backend

      - name: Run backend tests
        run: pytest
        working-directory: clinicq_backend

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: npm ci --prefer-offline --no-audit --progress=false
        working-directory: clinicq_frontend

      - name: Lint frontend with ESLint
        run: npm run lint
        working-directory: clinicq_frontend

      - name: Run frontend tests
        run: npm test -- --watchAll=false
        working-directory: clinicq_frontend
