name: Mobile CI

on:
  push:
    paths:
      - 'apps/mobile/**'
      - '.github/workflows/mobile-ci.yml'
  pull_request:
    paths:
      - 'apps/mobile/**'
      - '.github/workflows/mobile-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/mobile/package-lock.json

      - name: Install dependencies
        working-directory: apps/mobile
        run: npm ci --no-audit --progress=false

      - name: Lint mobile code
        working-directory: apps/mobile
        run: npm run lint

      - name: Type check mobile project
        working-directory: apps/mobile
        run: npm run typecheck

      - name: Run mobile tests
        working-directory: apps/mobile
        env:
          CI: 'true'
        run: npm test -- --coverage

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mobile-test-results
          path: apps/mobile/coverage/
          retention-days: 7
