name: Mobile EAS build

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'EAS build profile to use'
        required: false
        default: preview

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/mobile
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          npm run lint
          npm run typecheck
          npm run test

      - name: Build with EAS
        if: env.EXPO_TOKEN != ''
        env:
          EAS_NO_VCS: 1
        run: |
          PROFILE="${{ github.event.inputs.profile || 'preview' }}"
          npx eas build --platform android --profile "$PROFILE" --non-interactive

      - name: Skip build (missing token)
        if: env.EXPO_TOKEN == ''
        run: echo "EXPO_TOKEN secret is not configured; skipping EAS build step." && exit 0
